server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:departmentDb
# Link : http://localhost:9002/h2-console/

#spring.sleuth.sampler.probability=1

#management.endpoints.web.exposure.include=hystrix.stream