server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
#eureka.instance.hostname=localhost     # OR

spring:
  zipkin:
    base-url: http://localhost:9411/

#spring.sleuth.sampler.probability=1

#management.endpoints.web.exposure.include=hystrix.stream






